name: Android CI (Lint + Test + Build + Email)

on: push

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint
          chmod a+x ktlint
          ./ktlint --color

      - name: Run Android Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintDebug

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedDebugAndroidTest

  check-conflicts:
    name: Check Merge Conflicts
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-check-conflict@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew assembleDebug
      - name: Upload APK (optional)
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  notify:
    name: Send Email Notification
    runs-on: ubuntu-latest
    needs: build
    if: always()  # Runs even if previous jobs fail
    steps:
      - name: Send build status via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  # Your email (e.g., user@gmail.com)
          password: ${{ secrets.EMAIL_PASSWORD }}  # App password (NOT your main password)
          subject: "Android Build Status: ${{ job.status }}"
          body: |
            Build triggered by: ${{ github.actor }}
            Workflow: ${{ github.workflow }}
            Status: ${{ job.status }}
            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: your-email@example.com  # Replace with your email
          from: GitHub Actions
